apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: blazing
resources:
  - namespace.yml
  - secret.yml
  - deployment.yml
  - service.yml

helmCharts:
  - name: postgresql
    includeCRDs: true
    repo: https://charts.bitnami.com/bitnami
    version: 15.5.3
    releaseName: postgresql
    namespace: blazing
    valuesFile: values.yml