apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: blazing
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin123"
  POSTGRES_HOST: "postgresql"
  POSTGRES_DB: "blazing"
  # POSTGRES_PORT: "5432"
