apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: blazing
stringData:
  POSTGRES_USERNAME: "admin"      # Cambiado para coincidir con el código
  POSTGRES_PASSWORD: "admin123"   # Corregido el typo (agregada la T)
  POSTGRES_DB: "blazing"
  POSTGRES_HOST: "postgresql"     # Añade esta línea para que la API sepa a dónde ir